### PR TITLE
Integrate jest and spectron

### PR DESCRIPTION
**Pull request by SerhatKayaa**
You can read more via this link
https://circleci.com/blog/electron-testing/
if you test your code, just use npm run test
i left you an example in the __test__

### CODE REVIEW

**Comment by acrosman** [comment]
@SerhatKayaa thank you for doing this fix for #27.  Could you also include an update to the package.json to add the new dev dependencies of Jest and Spectron as well? I can resolve any issues that come up around the package-lock.json in my own commit (those get ugly in PRs). Also please include a newline at the end of the new test file.

**Comment by acrosman** [comment]
Thank you for continuing to work on this.  Looks like this draft now moves several of the app files into a `src` directory.  Can you either explain that choice or revise again to undo that part of the changes.

**Comment by SerhatKayaa** [comment]
Sorry for late response, Main src folder is general approach in javascript world. I think you should seperate your folder in src directory.I tried that i change the jest rootDirectory then i get an error without src folder, I'll share you two different electron app, you can look at that project structure. Thank you
https://github.com/martpie/museeks
https://github.com/microsoft/vscode

**Comment by acrosman** [comment]
Sure, although there are plenty of electron projects that elect to use `/app` or `/app/src`. More importantly when you moved everything you didn't update any of the internal references so if you run `npm start` in your branch nothing works. Jest's [roots directive](https://jestjs.io/docs/en/configuration#roots-arraystring) should allow you to set the app directory.  A fully project refactor is something I'm open to considering but that would be a separate issue from just enabling a testing framework.

**Comment by SerhatKayaa** [comment]
I think,it's okey right now, can you check this code ?

**Comment by acrosman** [comment]
The current PR seems to delete all the main project files.

**Pull request closed without merging**
